#!/usr/bin/env python
import re,sys,os,getopt
from sys import exit
USAGE = """Usage:  -l <list_type_name> -- for list template
        -t <"key_typename,value_typename"> -- for hash table template
        -o <output_directory> -- optional
        -i -- generate implementation header file
        -I -- generate only the implementation header file
"""
# template list 
TEMPLATE_LIST_CODE = 'templatelist.c'
TEMPLATE_LIST_CODE_SUFFIX = 'list.c'
TEMPLATE_LIST_HEADER = 'templatelist.h'
TEMPLATE_LIST_HEADER_SUFFIX = 'list.h'
TEMPLATE_LIST_IMP_HEADER = 'templatelist_imp.h'
TEMPLATE_LIST_IMP_HEADER_SUFFIX = 'list_imp.h'
# template hash table
TEMPLATE_HASHTABLE_CODE = 'templatehashtable.c'
TEMPLATE_HASHTABLE_HEADER = 'templatehashtable.h'
TEMPLATE_HASHTABLE_IMP_HEADER = 'templatehashtable_imp.h'
TEMPLATE_HASHTABLE_TYPES_HEADER = 'templatehashtabletypes.h'
TEMPLATE_HASHTABLE_CODE_SUFFIX = 'hashtable.c'
TEMPLATE_HASHTABLE_HEADER_SUFFIX = 'hashtable.h'
TEMPLATE_HASHTABLE_IMP_HEADER_SUFFIX = 'hashtable_imp.h'
TEMPLATE_HASHTABLE_TYPES_HEADER_SUFFIX = 'hashtabletypes.h'

TEMPLATE_FILES = [TEMPLATE_LIST_HEADER
    ,TEMPLATE_LIST_CODE
    ,TEMPLATE_LIST_IMP_HEADER
    ,TEMPLATE_HASHTABLE_CODE
    ,TEMPLATE_HASHTABLE_HEADER
    ,TEMPLATE_HASHTABLE_IMP_HEADER
    ,TEMPLATE_HASHTABLE_TYPES_HEADER]

TEMPLATE_DIR = '/home/uofkuv/453/Structures/template/templates/'
ARG_OPTIONS = 'l:t:o:iIh'
OUTPUT_DIR = './'
GENERATE_IMPLEMENTATION_HEADER = False
GENERATE_TEMPLATE_FILES = True

def checkOutputDir(dir):
    if os.path.exists(dir):
        if os.path.isdir(dir):
            if os.access(dir,os.W_OK):
                return True
            else:
                print 'Error: do not have write permission for '+dir
        else:
            print 'Error: '+dir+' is not a directory'
    else:
        print 'Error: '+dir+' does not exist'

def subContents(contents,subs):
    for sub in subs:
        contents = re.sub(sub[0],sub[1],contents)
    return contents

def templatize(filein,fileout,subs):
    with open(filein,'r') as f:
        contents = f.read()
        # print 'opened template file'
        contents = subContents(contents,subs)
        # print 'replaced template file contents'
    with open(fileout,'w') as f:
        f.write(contents)
        # print 'wrote new template file contents'

def create_template_hashtable(template_type):
    splits = template_type.split(',')
    key = splits[0]
    value = splits[1]
    entry_name = key+'K'+value+'V'
    lower_entry_name = entry_name.lower()
    list_type = entry_name+'Entry'

    subs = [(r'\$KK\$',key.upper())
        ,(r'\$Kk\$',key)
        ,(r'\$kk\$',key.lower())
        ,(r'\$VV\$',value.upper())
        ,(r'\$Vv\$',value)
        ,(r'\$vv\$',value.lower())]

    if GENERATE_TEMPLATE_FILES:
        # Create the bucket structure
        create_template_list(list_type)
        create_template_list_imp_header(list_type)
        sub = [(r'typedef.*;','#include "' + lower_entry_name + TEMPLATE_HASHTABLE_TYPES_HEADER_SUFFIX + '"')]
        templatize(OUTPUT_DIR + list_type.lower() + TEMPLATE_LIST_IMP_HEADER_SUFFIX,OUTPUT_DIR + list_type.lower() + TEMPLATE_LIST_IMP_HEADER_SUFFIX,sub)

        templatize(TEMPLATE_DIR + TEMPLATE_HASHTABLE_CODE,OUTPUT_DIR + lower_entry_name + TEMPLATE_HASHTABLE_CODE_SUFFIX,subs)
        templatize(TEMPLATE_DIR + TEMPLATE_HASHTABLE_HEADER,OUTPUT_DIR + lower_entry_name + TEMPLATE_HASHTABLE_HEADER_SUFFIX,subs)
        templatize(TEMPLATE_DIR + TEMPLATE_HASHTABLE_TYPES_HEADER,OUTPUT_DIR + lower_entry_name + TEMPLATE_HASHTABLE_TYPES_HEADER_SUFFIX,subs)

    if GENERATE_IMPLEMENTATION_HEADER:
        templatize(TEMPLATE_DIR + TEMPLATE_HASHTABLE_IMP_HEADER,OUTPUT_DIR + lower_entry_name + TEMPLATE_HASHTABLE_IMP_HEADER_SUFFIX,subs)

def create_template_list_imp_header(template_type):
    upper = template_type.upper()
    lower = template_type.lower()

    subs = [(r'\$\$',template_type)
        ,(r'\$\^\^\$',upper)
        ,(r'\$v\$',lower)]
    templatize(TEMPLATE_DIR+TEMPLATE_LIST_IMP_HEADER,OUTPUT_DIR+lower+TEMPLATE_LIST_IMP_HEADER_SUFFIX,subs)

def create_template_list(template_type):
    # print 'Creating template list of type: '+template_type
    upper = template_type.upper()
    lower = template_type.lower()

    subs = [(r'\$\$',template_type)
        ,(r'\$\^\^\$',upper)
        ,(r'\$v\$',lower)]

    if GENERATE_TEMPLATE_FILES:

        templatize(TEMPLATE_DIR+TEMPLATE_LIST_CODE,OUTPUT_DIR+lower+TEMPLATE_LIST_CODE_SUFFIX,subs)
        templatize(TEMPLATE_DIR+TEMPLATE_LIST_HEADER,OUTPUT_DIR+lower+TEMPLATE_LIST_HEADER_SUFFIX,subs)

    if (GENERATE_IMPLEMENTATION_HEADER):
        create_template_list_imp_header(template_type)
    # templatize(TEMPLATE_DIR+TEMPLATE_LIST_IMP_HEADER,OUTPUT_DIR+lower+TEMPLATE_LIST_IMP_HEADER_SUFFIX,subs)


if __name__ == '__main__':
    # print 'Check TEMPLATE_DIR'
    # check that template directory exists in working directory
    if os.path.exists(TEMPLATE_DIR):
        if not os.path.isdir(TEMPLATE_DIR):
            print 'Template directory does not exist'
            exit(2)
    else:
        print 'Template directory does not exist'
        exit(2)
    # print 'Check that template files exist'
    # check that template files exist
    for template_file in TEMPLATE_FILES:
        if not os.path.exists(TEMPLATE_DIR+template_file):
            print 'Template file <'+template_file+'> does not exist'
            exit(2)

    # print 'Arguments: ' + str(sys.argv)
    # print 'Check CL args'
    try:
        opts,args = getopt.getopt(sys.argv[1:],ARG_OPTIONS)
    except getopt.GetoptError:
        print USAGE
        exit(2)

    # print 'Opts: '+str(opts)
    # print 'Args: '+str(args)
    # print 'Check only one option'
    # if len(opts) != 1:
    #     print 'Specify one option'
    #     print USAGE
    #     # print opts
    #     exit(2)


    # print 'Execute'
    # print opts
    for opt in opts:
        # print opt
        if opt[0] == '-l':
            executee = create_template_list
            earg = opt[1]
            # create_template_list(opt[1])
        elif opt[0] == '-t':
            executee = create_template_hashtable
            earg = opt[1]
        elif opt[0] == '-o':
            if checkOutputDir(opt[1]):
                OUTPUT_DIR = opt[1]
            else:
                exit(2)
        elif opt[0] == '-i':
            GENERATE_IMPLEMENTATION_HEADER = True
        elif opt[0] == '-I':
            GENERATE_IMPLEMENTATION_HEADER = True
            GENERATE_TEMPLATE_FILES = False
        elif opt[0] == '-h':
            print USAGE
            exit(0)
        else:
            print 'Error: unrecognized option '+opt[0]
            print USAGE
            exit(2)
    if 'executee' in globals():
        executee(earg)
    else:
        print 'Error: must choose a data structure to generate'
        print USAGE
        exit(2)















